./quad < ./errors/error2_1.txt
./quad < ./errors/error2_2.txt
./quad < ./errors/error2_3.txt
./quad < ./errors/error2_4.txt
./quad < ./errors/error3_1.txt
./quad < ./errors/error3_2.txt
./quad < ./errors/error3_3.txt
./quad < ./errors/error3_4.txt
./quad < ./errors/error4_1.txt
./quad < ./errors/error4_2.txt
./quad < ./errors/error4_3.txt
./quad < ./errors/error4_4.txt
